# https://devenv.sh/integrations/github-actions/#complete-example
name: "Build and Release"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv ci

      - shell: devenv shell bash -e {0}
        run: |
          hello
          # https://stackoverflow.com/a/75641511
          nix-channel --add https://nixos.org/channels/nixpkgs-unstable
          nix-channel --update

      - run: devenv shell build

      # https://github.com/softprops/action-gh-release/blob/c9b46fe7aad9f02afd89b12450b780f52dacfb2d/README.md?plain=1#L45-L47
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # pin@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: say.tar.gz

# https://github.com/softprops/action-gh-release/blob/c9b46fe7aad9f02afd89b12450b780f52dacfb2d/README.md?plain=1#L220-L225
permissions:
  contents: write
